# theme: jekyll-theme-leap-day
remote_theme: mmistakes / minimal-mistakes
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
title: Harikrishnan Suresh
description: MS Robotic Systems Development, Robotics Institute, Carnegie Mellon University
github:
  is_project_page: false
